using COMP2139___assignment2.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace comp2147.Services.Pdf;

public class TicketPdfDocument(OrderItem ticket, byte[] qrImage) : IDocument
{
    private readonly OrderItem _ticket = ticket;
    private readonly byte[] _qrImage = qrImage;

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);

            // Header
            page.Header().Element(header =>
            {
                header.AlignCenter();
                header.Text($"Ticket for {_ticket.Event.Title}")
                      .FontSize(22)
                      .Bold();
            });

            // Content
            page.Content().Column(col =>
            {
                col.Item().Text($"Name: {_ticket.Order.User.FullName}").FontSize(14);
                col.Item().Text($"Email: {_ticket.Order.User.Email}").FontSize(14);
                col.Item().Text($"Event Date: {_ticket.Event.StartDate:MMMM dd, yyyy h:mm tt}").FontSize(14);
                col.Item().Text("Scan QR code at event entry:").FontSize(14).Bold();

               

                col.Item().Text(""); // Empty line

                col.Item().Element(e =>
                {
                    e.AlignCenter();
                    e.Text("Thank you for purchasing!")
                        .FontSize(12)
                        .Italic();
                });
            });

            // Footer
            page.Footer().Element(footer =>
            {
                footer.AlignCenter();
                footer.Text("Generated by Ricardo - 2025");
            });
        });
    }
}